plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.16.1'
}

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

loom {
    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    runConfigs.configureEach {
        ideConfigGenerated = true
    }
}

sourceSets {
    main {
        java.srcDir file('../common/src/main/java')
        resources.srcDir file('../common/src/main/resources')
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$rootProject.minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.11:2025.12.20@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    modImplementation "com.terraformersmc:modmenu:$rootProject.modmenu_version"

    implementation "de.marhali:json5-java:3.0.0"
    include "de.marhali:json5-java:3.0.0"
}

def resourceTargets = ['fabric.mod.json']
def replaceProperties = [
        mod_version: mod_version, mod_group: mod_group, mod_name: mod_name,
        mod_id     : mod_id, mod_description: mod_description, mod_authors: mod_authors,
        mod_license: mod_license, mod_tracker: mod_tracker
]

processResources {
    inputs.properties replaceProperties

    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}
