plugins {
}

allprojects {
    group = rootProject.mod_group
    version = rootProject.mod_version + "+" + rootProject.minecraft_version

    repositories {
        mavenCentral()
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
    }
}

subprojects {
    apply plugin: 'maven-publish'

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    plugins.withId('java') {
        dependencies {
            compileOnly 'org.projectlombok:lombok:1.18.32'
            annotationProcessor 'org.projectlombok:lombok:1.18.32'

            testCompileOnly 'org.projectlombok:lombok:1.18.32'
            testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'

            implementation 'org.jetbrains:annotations:20.1.0'
        }

        java {
            withSourcesJar()
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
    }

    plugins.withId('java') {
        base {
            archivesName = "$rootProject.mod_name" + "-" + "$project.name".toUpperCase()
        }
    }

    publishing {
        repositories {
            maven {
                name = "octo"
                url = "https://maven.octo-studios.com/releases"
                credentials(PasswordCredentials)
                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
    }

    plugins.withId('java') {
        publishing {
            publications {
                maven(MavenPublication) {
                    groupId = group
                    artifactId = project.mod_id + "-" + project.name
                    version = version
                    from components.java
                }
            }
        }
    }
}
