version=0.7.0+26.1.2
group=it.hurts.shatterbyte.shatterlib
java_version=25

minecraft_version=26.1.2
mod_name=ShatterLib
mod_author=Shatterbyte
mod_id=shatterlib
license=All Rights Reserved
credits=
description=Collection of shared code for Shatterbyte's mods
mod_tracker=https://github.com/SSKirillSS/octo-lib/issues
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1

fabric_version=0.152.1+26.1.2
fabric_loader_version=0.19.1

modmenu_version=18.0.0-alpha.8
sodium_version=0.8.12+mc26.1.2
iris_version=1.10.9+26.1

neoforge_version=26.1.2.76
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false
