# Compile arguments
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.7.0
mod_group = it.hurts.shatterbyte.byteapi
mod_name = Byte
mod_id = byte
mod_description = Collection of shared code for Shatterbyte\' mods
mod_authors = Shatterbyte
mod_license = All Rights Reserved
mod_tracker = https://github.com/SSKirillSS/octo-lib/issues
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.1
fabric_api_version = 0.145.4+26.1.2
neoforge_version = 26.1.2.7-beta
modmenu_version = 18.0.0-alpha.8
