version=0.7.0-beta.1+26.2
group=it.hurts.shatterbyte.shatterlib
java_version=25

minecraft_version=26.2
mod_name=ShatterLib
mod_author=Shatterbyte
mod_id=shatterlib
license=All Rights Reserved
credits=
description=Collection of shared code for Shatterbyte's mods
mod_tracker=https://github.com/SSKirillSS/octo-lib/issues
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

modmenu_version=20.0.0-beta.4
sodium_version=0.9.0+mc26.2
iris_version=1.11.1+26.2

neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false
